const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  id: Number, // Auto-generated by MongoDB
  password: { type: String, required: true },
});

module.exports = mongoose.model('User', userSchema);
