const mongoose = require('mongoose');

const user = new mongoose.Schema({
  personalid: Number, // Auto-generated by MongoDB
  hashedPassword: { type: String, required: true },
  role: { type: String, enum: ['voter', 'administrator'], default: 'voter' },
});

module.exports = mongoose.model('User', user);
module.exports = user;